package com.nkyrim.itapp.settings;

/**
 * Enum containing all the acceptable Keys for the settings storage. New settings must be added here
 */
public enum Key {
	HYDRA, PITHIA, AETOS,
	HYDRA_NAME, HYDRA_USERNAME, HYDRA_PASSWORD, HYDRA_LAST_LOGIN,
	PITHIA_NAME, PITHIA_USERNAME, PITHIA_PASSWORD, PITHIA_LAST_LOGIN,
	AETOS_NAME, AETOS_USERNAME, AETOS_PASSWORD, AETOS_LAST_LOGIN,
	NOTIFICATIONS_MAX, NOTIFICATIONS_ACTIVATION, NOTIFICATIONS_INTERVAL,
	DOWNLOADS, COURSES,  TIMETABLE,
	MAIL_DELETE_CONFIRM_DISABLED,
	IS_FIRST_RUN
}
